### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by mosrainis** [mosrainis/nasa-tracker#1]
- [x] Add a fixed Nav-Menu at the left side of web application
- [ ] Fix the header items and the link inside them
- [ ] Optimize the Nasa-Tracker module
